### ISSUE TITLE
Add “Today in History” to homepage

### ISSUE THREAD

**Issue by hesyifei** [TheStanfordDaily/archives-web#21]
Fetch first page’s first article title and display it?

**Comment by hesyifei** [comment]
Use API such as https://history.muffinlabs.com/ and link that day's (or the closest next day) and the following paper.

Maybe also mark down some important days for Stanford? Store that as a separate file in `archives-text`?

**Comment by epicfaace** [comment]
Why would we need https://history.muffinlabs.com/? Are you thinking of combining the data from that API and a link to a specific article in the archives?
