### ISSUE TITLE
corrections

### ISSUE THREAD

**Issue by ufxela** [TheStanfordDaily/archives-web#60]
create a form on frontend for users to create and submit corrections to articles. Then, someone at TSD needs to approve the changes, and run the pipeline (to be implemented, see: #55) to propagate the changes.

**Comment by epicfaace** [comment]
Sounds good -- so maybe submitting the form would automatically make a pull request on our repo?

**Comment by epicfaace** [comment]
We could use this which is super cool -- https://dev.to/teamhive/triggering-github-actions-using-repository-dispatches-39d1

basically, submitting the form would call an HTTP endpoint, which triggers the github action that makes the PR
