### ISSUE TITLE
better long search queries

### ISSUE THREAD

**Issue by ufxela** [TheStanfordDaily/archives-web#71]
currently, when you make a long search query w/ cloudsearch, it seems to not find results even if you took an exact excerpt from an article. To fix this, consider "or"ing together phrases or words from long search queries

https://stackoverflow.com/questions/31668928/amazon-cloudsearch-matching-long-strings-against-domain-documents

**Comment by epicfaace** [comment]
Is this also true when using the Lucene syntax?
