### ISSUE TITLE
First page of results from cloudsearch is not shown

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/archives-web#73]
Currently, on https://archives.stanforddaily.com/, the first page of results is not shown.

1. Inspect network requests from devtools, and search for something.
1. Note that the following request is sent:

https://ehabp6fuc5.execute-api.us-east-1.amazonaws.com/prod?q=test&size=20&start=20&highlight.article_text=%7Bformat:%27html%27,max_phrases:5%7D&fq=publish_date:[%271892-01-01T12:00:00Z%27,%272015-01-02T12:00:00Z%27]

However, I believe we should _actually_ be sending the following query:

https://ehabp6fuc5.execute-api.us-east-1.amazonaws.com/prod?q=test&size=20&start=0&highlight.article_text=%7Bformat:%27html%27,max_phrases:5%7D&fq=publish_date:[%271892-01-01T12:00:00Z%27,%272015-01-02T12:00:00Z%27]

**Comment by ufxela** [comment]
Woah this is a really good catch. It fixes #71 (no results were shown b/c there are <20 results for long, specific queries)! Also fixes the Tiger Woods / Kabir thing, cause that also had < 20 results!
