### ISSUE TITLE
Leaving "article text" empty in search gives a title "Search results for undefined"

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/archives-web#78]
When I search with another text box that isn't "article text", the title of the page says "Search results for undefined".

See, for example, http://localhost:3000/search?article_type_advertisement=true&article_type_article=true&page=1&pagelen=20&title=test&year_end=2014&year_start=1892

Instead, we should have whatever text the user typed in, in the other textbox.

**Comment by ufxela** [comment]
fixed in #83
