### ISSUE TITLE
some articles do not match up with text

### ISSUE THREAD

**Issue by ufxela** [TheStanfordDaily/archives-web#88]
e.g. https://d148m2cwwi25lc.cloudfront.net/1894/01/08?page=1&section=MODSMD_ARTICLE10#article

not sure how often this occurs, but I couldn't find another example in the 5 minutes i spent looking.

**Comment by ufxela** [comment]
#60 might be helpful in determining how big an issue this is

**Comment by ufxela** [comment]
ok this is actually a pretty big problem, and it's because articles from day N are being linked back to article texts from day N-1

**Comment by epicfaace** [comment]
Also, the link you linked to tries to grab text from https://raw.githubusercontent.com/TheStanfordDaily/archives-text/master/1894/01/07/MODSMD_ARTICLE10.article.txt, but this file doesn't even exist. In fact, we don't have a day for Jan 7, 1894 in the archives-text repo: see https://github.com/TheStanfordDaily/archives-text/tree/master/1894/01
